# Generated by Django 3.2.7 on 2022-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('useremail', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=5)),
                ('userbirth', models.DateField()),
                ('career', models.CharField(max_length=10)),
                ('resident', models.CharField(max_length=5)),
                ('received_mail', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='StoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RowNumber', models.TextField()),
                ('REF_WP', models.TextField()),
                ('CAT1', models.TextField()),
                ('CAT2', models.TextField()),
                ('MEMO_TIME', models.TextField()),
                ('SERIAL_NO', models.TextField()),
                ('stitle', models.TextField()),
                ('xbody', models.TextField()),
                ('xurl', models.TextField()),
                ('idpt', models.TextField()),
                ('address', models.TextField()),
                ('fileurl', models.TextField()),
                ('info', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('MRT', models.TextField()),
            ],
            options={
                'db_table': 'storymap',
            },
        ),
        migrations.CreateModel(
            name='Survey_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('Question1', models.CharField(max_length=20)),
                ('Question2', models.CharField(max_length=20)),
                ('Question3', models.CharField(max_length=20)),
                ('Question4', models.CharField(max_length=20)),
                ('Question5', models.CharField(max_length=20)),
                ('Question6', models.CharField(max_length=20)),
                ('Question7', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'survey_outcome',
            },
        ),
    ]
